apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - ./resources/loki-storage-secret.yaml
  - ./resources/loki.yaml
  - ./resources/mackerel-apikey.yaml
  - ./resources/namespace.yaml
  - ./resources/otelcol-agent-role.yaml
  - ./resources/otelcol-agent-rolebinding.yaml
  - ./resources/otelcol-agent-sa.yaml
  - ./resources/otelcol-agent.yaml
  - ./resources/otelcol-clusteragent-role.yaml
  - ./resources/otelcol-clusteragent-rolebinding.yaml
  - ./resources/otelcol-clusteragent-sa.yaml
  - ./resources/otelcol-clusteragent.yaml
  - ./resources/otelcol-gateway-role.yaml
  - ./resources/otelcol-gateway-rolebinding.yaml
  - ./resources/otelcol-gateway-sa.yaml
  - ./resources/otelcol-gateway-ta-role.yaml
  - ./resources/otelcol-gateway-ta-rolebinding.yaml
  - ./resources/otelcol-gateway-ta-sa.yaml
  - ./resources/otelcol-gateway.yaml
  - ./resources/prometheus.yaml
