apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus-operator

resources:
  - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.87.0/bundle.yaml
