apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: influxdb

resources:
  - ./resources/influxdb.yaml
  - ./resources/monitor.yaml
  - ./resources/namespace.yaml
  - ./resources/persistent-volume-claim.yaml
  - ./resources/persistent-volume.yaml
  - ./resources/service.yaml
