apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/cloudnative-pg-monitor.yaml
  - https://github.com/cloudnative-pg/cloudnative-pg/releases/download/v1.28.0/cnpg-1.28.0.yaml
