domainFilters:
  - ggrel.net
  - noa.pp.ua
  - rokoucha.net
  - sayn-wittgenste.in

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: apiKey

extraArgs:
  - --default-targets=materia.ggrel.net
  - --force-default-targets
  - --ignore-ingress-tls-spec
  - --txt-owner-id=materia

policy: sync

logLevel: debug

provider:
  name: cloudflare
