apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: eck-operator
    releaseName: elastic-operator
    namespace: elastic-system
    version: 3.2.0
    repo: https://helm.elastic.co
    includeCRDs: true

resources:
  - ./resources/namespace.yaml
