apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: teamspeak

resources:
  - ./resources/namespace.yaml
  - ./resources/service.yaml
  - ./resources/teamspeak.yaml
  - ./resources/teamspeak-data.yaml
