apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opentelemetry-collector

resources:
  - ./resources/crb.yaml
  - ./resources/namespace.yaml
  - ./resources/opentelemetry-collector.yaml
  - ./resources/rbac.yaml
