apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opentelemetry-collector

resources:
  - ./resources/crb.yaml
  - ./resources/mackerel-apikey.yaml
  - ./resources/namespace.yaml
  - ./resources/nodeport.yaml
  - ./resources/opentelemetry-collector.yaml
  - ./resources/otelcol-gateway.yaml
  - ./resources/rbac.yaml
  - ./resources/vaxila-apikey.yaml
