apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: redis-operator
    releaseName: redis-operator
    namespace: redis-operator
    version: "2.1.1"
    repo: https://ot-container-kit.github.io/helm-charts
    includeCRDs: true
    valuesInline:
      featureGates:
        GenerateConfigInInitContainer: true

resources:
  - ./resources/namespace.yaml
