apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: synology-csi

resources:
  - ./resources/beryllium-iscsi.yaml
  - ./resources/beryllium-nfs.yaml
  - ./resources/client-info-secret.yaml
  - https://raw.githubusercontent.com/SynologyOpenSource/synology-csi/v1.2.1/deploy/kubernetes/v1.20/controller.yml
  - https://raw.githubusercontent.com/SynologyOpenSource/synology-csi/v1.2.1/deploy/kubernetes/v1.20/csi-driver.yml
  - https://raw.githubusercontent.com/SynologyOpenSource/synology-csi/v1.2.1/deploy/kubernetes/v1.20/namespace.yml
  - https://raw.githubusercontent.com/SynologyOpenSource/synology-csi/v1.2.1/deploy/kubernetes/v1.20/node.yml

patches:
  - path: ./patches/node-k0s.yaml
