apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nebraska

helmCharts:
  - name: nebraska
    releaseName: nebraska
    namespace: nebraska
    version: 2.0.0
    repo: https://flatcar.github.io/nebraska
    valuesFile: ./values.yaml

resources:
  - ./resources/monitor-postgresql.yaml
  - ./resources/namespace.yaml
  - ./resources/nebraska-secrets.yaml
  - ./resources/postgresql.yaml
  - ./resources/tls.yaml
