config:
  auth:
    mode: oidc
    oidc:
      existingSecret: nebraska-secrets
      issuerURL: https://auth.ggrel.net/application/o/nebraska/
      managementURL: https://auth.ggrel.net/
      logoutURL: https://auth.ggrel.net/application/o/nebraska/end-session/
      adminRoles: Nebraska Admin
      viewerRoles: Nebraska Viewer
      rolesPath: groups

  database:
    passwordExistingSecret:
      enabled: true
      name: postgresql-app
      key: password

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: haproxy
  hosts:
    - nebraska.ggrel.net
  tls:
    - secretName: tls
      hosts:
        - nebraska.ggrel.net

postgresql:
  enabled: false
